### ISSUE TITLE
How to build the source in Ubuntu 20.04.1 LTS?

### ISSUE THREAD

**Issue by p3t3r67x0** [nosferalatu/SimpleConcurrentGPUHashTable#3]
I wonder if there is a way to build the GPU Hash Table under Ubuntu Linux?

What I did so far..

```
cd build
cmake .. -G 'Unix Makefiles'
cmake --build . --config Release
```

Which gives me this result...

```
[ 25%] Building CXX object CMakeFiles/test.dir/src/main.cpp.o
/home/ubuntu/git/SimpleGPUHashTable/src/main.cpp: In function ‘Time start_timer()’:
/home/ubuntu/git/SimpleGPUHashTable/src/main.cpp:47:51: error: could not convert ‘std::chrono::_V2::system_clock::now()’ from ‘time_point<std::chrono::_V2::system_clock,[...]>’ to ‘time_point<std::chrono::_V2::steady_clock,[...]>’
   47 |     return std::chrono::high_resolution_clock::now();
      |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
      |                                                   |
      |                                                   time_point<std::chrono::_V2::system_clock,[...]>
/home/ubuntu/git/SimpleGPUHashTable/src/main.cpp: In function ‘double get_elapsed_time(Time)’:
/home/ubuntu/git/SimpleGPUHashTable/src/main.cpp:52:55: error: conversion from ‘time_point<std::chrono::_V2::system_clock,[...]>’ to non-scalar type ‘time_point<std::chrono::_V2::steady_clock,[...]>’ requested
   52 |     Time end = std::chrono::high_resolution_clock::now();
      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
make[2]: *** [CMakeFiles/test.dir/build.make:63: CMakeFiles/test.dir/src/main.cpp.o] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/test.dir/all] Fehler 2
make: *** [Makefile:84: all] Fehler 2
``` 

Any idea what I could do right?

**Comment by mewim** [comment]
Hi @p3t3r67x0. I also tried to build this for Ubuntu and I managed to get it work on a Google Colab machine with Tesla P100 GPU with some changes:
- Change the return type of `std::chrono::high_resolution_clock::now()` to `std::chrono::time_point<std::chrono::high_resolution_clock>`.
- Remove the include for `"windows.h"` header file.
- Use `sm_60` architect (you may not need it if you are running a lower CUDA version).

My changes are pushed to GitHub: https://github.com/nosferalatu/SimpleGPUHashTable/compare/master...mewim:9e8a4cd

**Comment by samsdolphin** [comment]
Thank you @mewim for your answer which makes the code successfully run on my desktop.

For the `architect` thing you mention, I suggest modifying it based on the installed CUDA version. For me, I am using 2080Ti and the `sm_75` fits me the most.
