### ISSUE TITLE
Wrong kernel call in lookup function

### ISSUE THREAD

**Issue by rehakvoj1** [nosferalatu/SimpleConcurrentGPUHashTable#8]
Hello @nosferalatu,
In file linearprobing.cu on the line 138 there is "insert" kernel called. But It's in the lookup function. So I suppose there should be called lookup kernel.

**Comment by nosferalatu** [comment]
You are correct. It should have been calling `gpu_hashtable_lookup`. I just pushed a commit that fixes this problem. Thanks!
